blueprint:
  name: OpenCode Permission Response Handler
  description: >
    Handles approve/reject actions from OpenCode permission notifications.
    
    This blueprint listens for notification actions (button taps) and sends
    the appropriate permission response via the OpenCode integration service.
    
    Works with both iOS and Android via the Home Assistant Companion app.
    
    Use this together with the OpenCode State Notifications blueprint.
  domain: automation
  author: ha-opencode
  source_url: https://gitlab.com/opencode-home-assistant/opencode-plugin/-/blob/main/blueprints/opencode_permission_response.yaml
  input: {}

mode: parallel
max_exceeded: silent

trigger:
  - platform: event
    event_type: mobile_app_notification_action

variables:
  # Get the action string
  action: "{{ trigger.event.data.action | default('') }}"
  
  # Check if this is an OpenCode action
  is_opencode_action: >
    {{ action.startswith('OPENCODE_APPROVE_') or action.startswith('OPENCODE_REJECT_') }}
  
  is_approve: "{{ action.startswith('OPENCODE_APPROVE_') }}"
  response: "{{ 'once' if is_approve else 'reject' }}"
  
  # Extract session_id from action name (after the prefix)
  session_id_from_action: >
    {% if action.startswith('OPENCODE_APPROVE_') %}
      {{ action[17:] }}
    {% elif action.startswith('OPENCODE_REJECT_') %}
      {{ action[16:] }}
    {% else %}
      
    {% endif %}
  
  # Get data passed from the notification
  # iOS uses action_data, Android might use data directly
  action_data: >
    {% if trigger.event.data.action_data is defined %}
      {{ trigger.event.data.action_data }}
    {% elif trigger.event.data.data is defined %}
      {{ trigger.event.data.data }}
    {% else %}
      {}
    {% endif %}
  
  session_id: "{{ action_data.session_id | default(session_id_from_action) }}"

condition:
  - condition: template
    value_template: "{{ is_opencode_action }}"

action:
  # Log for debugging
  - service: system_log.write
    data:
      message: >
        OpenCode permission response: action={{ action }}, is_approve={{ is_approve }}, 
        response={{ response }}, session_id={{ session_id }},
        action_data={{ action_data }}
      level: info
      logger: ha-opencode.permission

  # Check we have required data before calling service
  - condition: template
    value_template: "{{ session_id != '' }}"

  - service: opencode.respond_permission
    data:
      session_id: "{{ session_id }}"
      response: "{{ response }}"

  # Log success
  - service: system_log.write
    data:
      message: "OpenCode permission {{ response }} sent for session {{ session_id }}"
      level: info
      logger: ha-opencode.permission
