blueprint:
  name: OpenCode State Notifications
  description: >
    Send notifications to your mobile device when OpenCode sessions need attention.
    Notifies when:
    - A task completes (idle after working)
    - Permission is required (with approve/reject buttons)
    - An error occurs
    
    Works with both iOS and Android via the Home Assistant Companion app.
    
    Requires the Permission Response Handler blueprint to handle approve/reject actions.
  domain: automation
  author: ha-opencode
  source_url: https://github.com/your-repo/ha-opencode/blob/main/blueprints/opencode_state_notifications.yaml
  input:
    notify_service:
      name: Notification Service
      description: >
        The notification service to use (e.g., notify.mobile_app_your_phone).
      selector:
        text:
      default: "notify.mobile_app_phone"
    
    notify_on_complete:
      name: Notify on Task Complete
      description: Send a notification when a task completes (idle after working).
      default: true
      selector:
        boolean:
    
    notify_on_permission:
      name: Notify on Permission Required
      description: Send a notification with approve/reject buttons when permission is needed.
      default: true
      selector:
        boolean:
    
    notify_on_error:
      name: Notify on Error
      description: Send a notification when an error occurs.
      default: true
      selector:
        boolean:
    
    notification_channel:
      name: Notification Channel (Android)
      description: >
        Android notification channel name. 
        You can create channels in the Companion app settings.
      default: "OpenCode"
      selector:
        text:
    
    dashboard_path:
      name: Dashboard Path
      description: >
        Path to your OpenCode dashboard for click action (e.g., /lovelace/opencode).
        Leave empty to use default behavior.
      default: "/lovelace/opencode"
      selector:
        text:

mode: parallel
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: "opencode/+/state"
    id: state_change

variables:
  # The new state from the MQTT payload
  new_state: "{{ trigger.payload }}"
  
  # Extract device_id from topic: opencode/{device_id}/state
  device_id: "{{ trigger.topic.split('/')[1] }}"
  
  # Build the state_topic_base for entity lookup
  state_topic_base: "opencode/{{ device_id }}"
  
  # Find the device_id entity that has this state_topic_base in its attributes
  device_id_entity: >
    {% set ns = namespace(found='') %}
    {% for entity in states.sensor %}
      {% if entity.attributes.get('state_topic_base', '') == state_topic_base %}
        {% set ns.found = entity.entity_id %}
      {% endif %}
    {% endfor %}
    {{ ns.found }}
  
  # Check if we found the entity
  entity_found: "{{ device_id_entity != '' }}"
  
  # Derive other entity IDs from the device_id entity (they share the same base)
  entity_base: "{{ device_id_entity | replace('_device_id', '') if entity_found else '' }}"
  state_entity: "{{ (entity_base ~ '_state') if entity_found else '' }}"
  session_entity: "{{ (entity_base ~ '_session_title') if entity_found else '' }}"
  
  # Get values from entities (with defaults)
  previous_state: "{{ state_attr(state_entity, 'previous_state') | default('unknown') if entity_found else 'unknown' }}"
  project_name: "{{ state_attr(device_id_entity, 'device_name') | default('OpenCode') if entity_found else 'OpenCode' }}"
  command_topic: "{{ state_attr(device_id_entity, 'command_topic') | default('') if entity_found else '' }}"
  permission_id: "{{ state_attr(state_entity, 'permission_id') | default('') if entity_found else '' }}"
  permission_title: "{{ state_attr(state_entity, 'permission_title') | default('Permission needed') if entity_found else 'Permission needed' }}"
  error_message: "{{ state_attr(state_entity, 'error_message') | default('An error occurred') if entity_found else 'An error occurred' }}"
  session_title: "{{ states(session_entity) | default('Task finished') if entity_found else 'Task finished' }}"
  
  # Determine if this is a transition we care about
  was_working: "{{ previous_state == 'working' }}"

action:
  # Log for debugging (can be removed later)
  - service: system_log.write
    data:
      message: >
        OpenCode notification trigger: new_state={{ new_state }}, previous_state={{ previous_state }}, 
        device_id={{ device_id }}, entity_found={{ entity_found }}, was_working={{ was_working }}
      level: info
      logger: ha-opencode.blueprint

  - choose:
      # Permission Required (always notify, regardless of previous state)
      - conditions:
          - condition: template
            value_template: "{{ new_state == 'waiting_permission' }}"
          - condition: template
            value_template: !input notify_on_permission
        sequence:
          # Small delay to let permission attributes arrive
          - delay:
              milliseconds: 500
          - service: !input notify_service
            data:
              title: "OpenCode: Permission Required"
              message: "{{ project_name }}: {{ permission_title }}"
              data:
                tag: "opencode-permission-{{ device_id }}"
                channel: !input notification_channel
                importance: high
                priority: high
                ttl: 0
                clickAction: !input dashboard_path
                url: !input dashboard_path
                actions:
                  - action: "OPENCODE_APPROVE_{{ device_id }}"
                    title: "Approve"
                  - action: "OPENCODE_REJECT_{{ device_id }}"
                    title: "Reject"
                # Pass data needed for permission response
                action_data:
                  device_id: "{{ device_id }}"
                  permission_id: "{{ permission_id }}"
                  command_topic: "{{ command_topic }}"

      # Error Occurred (only after working)
      - conditions:
          - condition: template
            value_template: "{{ new_state == 'error' and was_working }}"
          - condition: template
            value_template: !input notify_on_error
        sequence:
          - service: !input notify_service
            data:
              title: "OpenCode: Error"
              message: "{{ project_name }}: {{ error_message }}"
              data:
                tag: "opencode-error-{{ device_id }}"
                channel: !input notification_channel
                importance: high
                priority: high
                ttl: 0
                clickAction: !input dashboard_path
                url: !input dashboard_path

      # Work Complete (idle after working)
      - conditions:
          - condition: template
            value_template: "{{ new_state == 'idle' and was_working }}"
          - condition: template
            value_template: !input notify_on_complete
        sequence:
          - service: !input notify_service
            data:
              title: "OpenCode: Task Complete"
              message: "{{ project_name }}: {{ session_title }}"
              data:
                tag: "opencode-complete-{{ device_id }}"
                channel: !input notification_channel
                clickAction: !input dashboard_path
                url: !input dashboard_path
