blueprint:
  name: OpenCode State Notifications
  description: >
    Send notifications to your mobile device when OpenCode sessions need attention.
    Notifies when:
    - A task completes (idle after working)
    - Permission is required (with approve/reject buttons)
    - An error occurs
    
    Works with both iOS and Android via the Home Assistant Companion app.
    
    Requires the Permission Response Handler blueprint to handle approve/reject actions.
  domain: automation
  author: ha-opencode
  source_url: https://github.com/your-repo/ha-opencode/blob/main/blueprints/opencode_state_notifications.yaml
  input:
    notify_device:
      name: Notification Target
      description: >
        The mobile device to send notifications to.
        Select your phone from the list (e.g., mobile_app_your_phone).
      selector:
        device:
          integration: mobile_app
    
    notify_on_complete:
      name: Notify on Task Complete
      description: Send a notification when a task completes (idle after working).
      default: true
      selector:
        boolean:
    
    notify_on_permission:
      name: Notify on Permission Required
      description: Send a notification with approve/reject buttons when permission is needed.
      default: true
      selector:
        boolean:
    
    notify_on_error:
      name: Notify on Error
      description: Send a notification when an error occurs.
      default: true
      selector:
        boolean:
    
    notification_channel:
      name: Notification Channel (Android)
      description: >
        Android notification channel name. 
        You can create channels in the Companion app settings.
      default: "OpenCode"
      selector:
        text:
    
    dashboard_path:
      name: Dashboard Path
      description: >
        Path to your OpenCode dashboard for click action (e.g., /lovelace/opencode).
        Leave empty to use default behavior.
      default: "/lovelace/opencode"
      selector:
        text:

mode: parallel
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: "opencode/+/state"

variables:
  # Extract the state topic base from the trigger
  state_topic_base: "{{ trigger.topic | replace('/state', '') }}"
  
  # Find the device_id entity that has this state_topic_base in its attributes
  device_id_entity: >
    {{ states.sensor | selectattr('attributes.state_topic_base', 'defined')
       | selectattr('attributes.state_topic_base', 'eq', state_topic_base)
       | map(attribute='entity_id') | first | default('') }}
  
  # Derive other entity IDs from the device_id entity
  entity_base: "{{ device_id_entity | replace('_device_id', '') }}"
  state_entity: "{{ entity_base }}_state"
  permission_entity: "{{ entity_base }}_permission"
  session_entity: "{{ entity_base }}_session_title"
  
  # Get values from entities
  previous_state: "{{ state_attr(state_entity, 'previous_state') }}"
  project_name: "{{ state_attr(device_id_entity, 'device_name') | default('OpenCode') }}"
  command_topic: "{{ state_attr(device_id_entity, 'command_topic') }}"
  device_id: "{{ states(device_id_entity) }}"
  
  # Get the notify service for the selected device
  notify_service: >
    {% set device_id = device_id(trigger.event.data.device_id if trigger.event is defined else '') %}
    {% for service in integration_entities('mobile_app') %}
      {% if device_id(service) == device_id %}
        notify.{{ service | replace('device_tracker.', '') }}
      {% endif %}
    {% endfor %}

condition:
  - condition: template
    value_template: >
      {{ device_id_entity != ''
         and trigger.payload in ['idle', 'waiting_permission', 'error']
         and previous_state == 'working' }}

action:
  - choose:
      # Permission Required
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'waiting_permission' }}"
          - condition: template
            value_template: !input notify_on_permission
        sequence:
          # Small delay to let permission attributes arrive
          - delay:
              milliseconds: 500
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            title: "OpenCode: Permission Required"
            message: "{{ state_attr(permission_entity, 'title') | default('Permission needed') }}"
            data:
              tag: "opencode-permission-{{ device_id }}"
              channel: !input notification_channel
              importance: high
              priority: high
              ttl: 0
              clickAction: !input dashboard_path
              url: !input dashboard_path
              actions:
                - action: "OPENCODE_APPROVE_{{ device_id }}"
                  title: "Approve"
                - action: "OPENCODE_REJECT_{{ device_id }}"
                  title: "Reject"
              # Pass data needed for permission response
              action_data:
                device_id: "{{ device_id }}"
                permission_id: "{{ state_attr(permission_entity, 'permission_id') }}"
                command_topic: "{{ command_topic }}"

      # Error Occurred
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'error' }}"
          - condition: template
            value_template: !input notify_on_error
        sequence:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            title: "OpenCode: Error"
            message: "{{ project_name }}: {{ state_attr(state_entity, 'error_message') | default('An error occurred') }}"
            data:
              tag: "opencode-error-{{ device_id }}"
              channel: !input notification_channel
              importance: high
              priority: high
              ttl: 0

      # Work Complete (idle after working)
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == 'idle' }}"
          - condition: template
            value_template: !input notify_on_complete
        sequence:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            title: "OpenCode: Task Complete"
            message: "{{ project_name }}: {{ states(session_entity) | default('Task finished') }}"
            data:
              tag: "opencode-complete-{{ device_id }}"
              channel: !input notification_channel
